"""empty message

Revision ID: f9c828adb6be
Revises: 
Create Date: 2020-08-26 06:56:36.020854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c828adb6be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('resourceChannelId', sa.String(length=30), nullable=False),
    sa.Column('originalChannelId', sa.String(length=30), nullable=False),
    sa.Column('subscriptAt', sa.DateTime(), nullable=True),
    sa.Column('resourceTitle', sa.String(length=255), nullable=False),
    sa.Column('resourceDescription', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('resourceChannelId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
