"""empty message

Revision ID: 654301276435
Revises: 7faf1c6d44dc
Create Date: 2020-10-25 02:48:18.589869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654301276435'
down_revision = '7faf1c6d44dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_category', sa.Column('assignable', sa.BOOLEAN(), nullable=False))
    op.add_column('video_category', sa.Column('channel_id', sa.String(length=24), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_category', 'channel_id')
    op.drop_column('video_category', 'assignable')
    # ### end Alembic commands ###
