"""empty message

Revision ID: b05465c87e60
Revises: 
Create Date: 2020-09-01 03:24:51.118918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05465c87e60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channelId', sa.String(length=24), nullable=False),
    sa.Column('channelTitle', sa.String(length=100), nullable=False),
    sa.Column('channelDescription', sa.String(length=100), nullable=False),
    sa.Column('channelCustomUrl', sa.String(length=1000), nullable=False),
    sa.Column('channelPublishedAt', sa.DateTime(), nullable=False),
    sa.Column('channelThumbnailsUrl', sa.String(length=200), nullable=False),
    sa.Column('channelCountry', sa.String(length=2), nullable=False),
    sa.Column('channelRelatedPlaylists', sa.String(length=24), nullable=False),
    sa.Column('channelViewCount', sa.Integer(), nullable=True),
    sa.Column('channelCommentCount', sa.Integer(), nullable=True),
    sa.Column('channelVideoCount', sa.Integer(), nullable=True),
    sa.Column('channelKeywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('channelTopicIds', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channelKeywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_playlist_items',
    sa.Column('videoId', sa.String(length=11), nullable=False),
    sa.Column('videoPublishedAt', sa.DateTime(), nullable=False),
    sa.Column('channelId', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('videoId')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resourceChannelId', sa.String(length=24), nullable=False),
    sa.Column('originalChannelId', sa.String(length=24), nullable=False),
    sa.Column('subscriptAt', sa.DateTime(), nullable=False),
    sa.Column('resourceTitle', sa.String(length=100), nullable=False),
    sa.Column('resourceDescription', sa.String(length=1000), nullable=True),
    sa.Column('writeTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_id',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('topicName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_detail',
    sa.Column('videoId', sa.String(length=11), nullable=False),
    sa.Column('title', sa.String(length=70), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('defaultAudioLanguage', sa.String(length=5), nullable=True),
    sa.Column('liveBroadcastContent', sa.String(), nullable=True),
    sa.Column('viewCount', sa.Integer(), nullable=True),
    sa.Column('likeCount', sa.Integer(), nullable=True),
    sa.Column('dislikeCount', sa.Integer(), nullable=True),
    sa.Column('favoriteCount', sa.Integer(), nullable=True),
    sa.Column('commentCount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['videoId'], ['channel_playlist_items.videoId'], ),
    sa.PrimaryKeyConstraint('videoId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_detail')
    op.drop_table('topic_id')
    op.drop_table('subscriptions')
    op.drop_table('channel_playlist_items')
    op.drop_table('channelKeywords')
    op.drop_table('channel')
    # ### end Alembic commands ###
