"""empty message

Revision ID: b1f047b6fefc
Revises: b05465c87e60
Create Date: 2020-09-02 18:22:22.977276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f047b6fefc'
down_revision = 'b05465c87e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies_comments',
    sa.Column('commentsId', sa.String(length=49), nullable=False),
    sa.Column('parentId', sa.String(length=26), nullable=False),
    sa.Column('videoId', sa.String(length=11), nullable=False),
    sa.Column('textOriginal', sa.String(), nullable=False),
    sa.Column('authorDisplayName', sa.String(), nullable=False),
    sa.Column('authorChannelId', sa.String(), nullable=False),
    sa.Column('likeCount', sa.Integer(), nullable=False),
    sa.Column('publishedAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('commentsId')
    )
    op.create_table('top_level_comment',
    sa.Column('CommentId', sa.String(length=26), nullable=False),
    sa.Column('videoId', sa.String(length=11), nullable=False),
    sa.Column('textOriginal', sa.String(), nullable=False),
    sa.Column('authorDisplayName', sa.String(), nullable=False),
    sa.Column('authorChannelId', sa.String(), nullable=False),
    sa.Column('likeCount', sa.Integer(), nullable=False),
    sa.Column('publishedAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('CommentId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_level_comment')
    op.drop_table('replies_comments')
    # ### end Alembic commands ###
